#!/usr/bin/env bash

set -euo pipefail

# Allow current home-manage configurationt to buld
export ALLOW_UNFREE=1
export ALLOW_UNSAFE=1

# Remove autogenerated files that get in the way of home-manager
./ingr/cleanup 

# Buld the new home-manager configuration
home-manager build --flake .#void switch --verbose --impure --extra-experimental-features nix-command --extra-experimental-features flakes
