# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot = {
      initrd = {
        availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
        kernelModules = [ "xe" "nvidia" "i915" "nvidia_drm" "nvidia_modeset" "nvidia_uvm" ];
      };
      kernelModules = [ "kvm-intel" ];
      blacklistedKernelModules = [ "serial8250" "tpm_crb" "tpm_tis" ];

      # https://wiki.archlinux.org/title/Intel_graphics#Crash/freeze_on_low_power_Intel_CPUs
      kernelParams = [ 
        "intel_idle.max_cstate=1" 
        "i915.enable_dc=0" 
        "i915.enable_psr=0"
        "ahci.mobile_lpm_policy=1" 
        "nvme_core.default_ps_max_latency_us=0"
        "nvme.noacpi=1"
        "pcie_aspm=off"
        "vmd.allow_msix=0"
        "8250.nr_uarts=0"
        "iommu.strict=1"
      ];
      extraModulePackages = [ ];
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/55e3191b-34ac-45f9-a0fd-a3b246bb5baa";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1123808c-135b-4c84-b4c1-6c317d567301".device = "/dev/disk/by-uuid/1123808c-135b-4c84-b4c1-6c317d567301";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A08D-1AA6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp44s0f0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
