categories:
    - name: Tech
      desc: Tech
      subscriptions:
        - name: go
          desc: Go Weekly
          url: https://cprss.s3.amazonaws.com/golangweekly.com.xml
        - name: rust
          desc: ""
          url: https://blog.rust-lang.org/feed.xml
